"""PLP (Product Listing / Jewellery) test case data — imported by add_plp_test_cases.py."""

from __future__ import annotations

PRE_01 = "PRE-01: Magento catalog reachable with published products in multiple categories"
PRE_02 = "PRE-02: Strapi product-landing-page published with hero and trust badges"
PRE_03 = "PRE-03: Test viewports: Mobile (≤390px), Tablet (~768px), Desktop (≥1280px)"
PRE_04 = "PRE-04: Browsers: Chrome, Safari, Firefox, Edge (latest)"
PRE_05 = "PRE-05: Logged-in and guest user accounts available for wishlist tests"

PRECONDITIONS_LIST = [
    ("PRE-01", "Magento catalog reachable with published products in multiple categories"),
    ("PRE-02", "Strapi product-landing-page published with hero and trust badges"),
    ("PRE-03", "Test viewports: Mobile (≤390px), Tablet (~768px), Desktop (≥1280px)"),
    ("PRE-04", "Browsers: Chrome, Safari, Firefox, Edge (latest)"),
    ("PRE-05", "Logged-in and guest user accounts available for wishlist tests"),
]

TEST_DATA_NOTES = [
    "Primary routes: /jewellery, /diamond-rings, /jewellery/diamond-rings",
    "Page size: 9 products per page; Load More appends next page",
    "URL params: minPrice, maxPrice, collection, occasion, diamondShape, fancyColour, category",
    "Sort is client state only — not persisted in URL",
    "Price filter uses client-side refinement for tax-index mismatch",
]

KNOWN_GAPS = [
    "No error/retry UI when Magento listing fetch fails (hook returns error, page ignores it)",
    "Sort selection lost on full page refresh (not in URL)",
    "Gift-finder entry skips SSR prefetch (slower first paint)",
    "Canonical URL points to CMS dev domain (sunnydiamonds-cms-dev.on-forge.com)",
]

# issue_id, jira, module, area, title, description, priority, status, test_ids, notes
ISSUES = [
    (
        "PLP-ISSUE-001",
        "SD-193",
        "PLP",
        "Error handling",
        "No error UI on listing fetch failure",
        "useMagentoJewelleryListing exposes error state but JewelleryProductPage never renders it. Users see empty skeleton or stale grid on API failure.",
        "P0",
        "Open",
        "PLP-029, PLP-030, PLP-088",
        "",
    ),
    (
        "PLP-ISSUE-002",
        "SD-194",
        "PLP",
        "Sort",
        "Sort not persisted in URL",
        "Sort value (featured, price-asc, etc.) is React state only. Refresh or share URL always resets to Featured; SSR prefetch always uses featured sort.",
        "P1",
        "Open",
        "PLP-018, PLP-022, PLP-067",
        "",
    ),
    (
        "PLP-ISSUE-004",
        "SD-196",
        "PLP",
        "Price filter",
        "Price total count inaccurate with active filter",
        "When price filter is active, totalCount uses client-refined page-1 length rather than Magento total_count — progress bar may under-report.",
        "P2",
        "Resolved",
        "PLP-023, PLP-036",
        "",
    ),
    (
        "PLP-ISSUE-005",
        "SD-197",
        "PLP",
        "SEO",
        "noIndex on ?category= primary listing URLs",
        "generateMetadata sets noIndex: true when ?category= is present on /jewellery — collection/occasion filtered PLPs may be excluded from indexing.",
        "P2",
        "Open",
        "PLP-082",
        "",
    ),
    (
        "PLP-ISSUE-006",
        "SD-198",
        "PLP",
        "Performance",
        "Gift-finder entry skips SSR prefetch",
        "shouldSkipJewelleryListingPrefetch returns true for gift-finder params — intentional but causes slower first paint vs standard PLP.",
        "P2",
        "Open",
        "PLP-090",
        "",
    ),
    (
        "PLP-ISSUE-007",
        "SD-199",
        "PLP",
        "Performance",
        "Hero LCP preload not wired to PLP",
        "preloadPlpHeroLcpImages used on Contact page but not jewellery PLP hero — missed LCP optimization.",
        "P3",
        "Resolved",
        "PLP-114",
        "",
    ),
    (
        "PLP-ISSUE-008",
        "SD-200",
        "PLP",
        "Architecture",
        "Dead collection fetch helper",
        "fetchMagentoJewelleryCollectionPage() in products.service.ts is defined but never called.",
        "P3",
        "Resolved",
        "PLP-113",
        "",
    ),
    (
        "PLP-ISSUE-009",
        "SD-201",
        "PLP",
        "SEO",
        "Canonical URL points to CMS dev domain",
        "Canonical link points to sunnydiamonds-cms-dev.on-forge.com/jewellery instead of production domain.",
        "P1",
        "Open",
        "PLP-092",
        "",
    ),
]

# id, area, scenario, steps, expected, priority, type, preconds, test_data, notes
TEST_CASES = [
    # A. Page Load
    ("PLP-001", "A. Page Load", "Open all-jewellery PLP", "Navigate to /jewellery", "Page loads; skeleton then product grid; no console errors", "P0", "Functional", PRE_01, "Route: /jewellery", ""),
    ("PLP-002", "A. Page Load", "Open category PLP (root path)", "Navigate to /diamond-rings", "Category PLP loads with rings products", "P0", "Functional", PRE_01, "Route: /diamond-rings", ""),
    ("PLP-003", "A. Page Load", "Open category PLP (nested path)", "Navigate to /jewellery/diamond-rings", "Same listing as root category path", "P1", "Functional", PRE_01, "Route: /jewellery/diamond-rings", ""),
    ("PLP-004", "A. Page Load", "Legacy redirect", "Open /jewellery-product", "Redirects to /jewellery", "P2", "Navigation", PRE_01, "/jewellery-product", ""),
    ("PLP-005", "A. Page Load", "CMS hero renders", "Load /jewellery with CMS hero configured", "Hero section visible above category nav", "P1", "CMS", PRE_02, "Route: /jewellery", ""),
    ("PLP-006", "A. Page Load", "Trust badges / guarantees bar", "Scroll to bottom of PLP", "Guarantees section renders CMS trust badges", "P2", "CMS", PRE_02, "Route: /jewellery", ""),
    ("PLP-007", "A. Page Load", "Loading skeleton", "Hard refresh on slow network", "JewelleryProductGridSkeleton shown during fetch", "P2", "UX", PRE_01, "Route: /jewellery", ""),
    ("PLP-008", "A. Page Load", "Route loading.tsx", "Navigate to /jewellery", "JewelleryListingPageSkeleton shown in Suspense boundary", "P2", "UX", PRE_01, "loading.tsx present", ""),
    ("PLP-009", "A. Page Load", "JSON-LD breadcrumb", "Inspect page source", "Breadcrumb JSON-LD script present", "P2", "SEO", PRE_01, "Route: /jewellery", ""),
    ("PLP-010", "A. Page Load", "JSON-LD ItemList", "Inspect page source with prefetched products", "ItemList JSON-LD with product names/urls", "P2", "SEO", PRE_01, "Route: /jewellery", ""),
    # B. Category Navigation
    ("PLP-011", "B. Category Nav", "All tab default", "Open /jewellery", "All tab active; products from all categories", "P0", "Functional", PRE_01, "Route: /jewellery", ""),
    ("PLP-012", "B. Category Nav", "Rings tab", "Click Rings in category nav", "URL updates; rings products shown", "P0", "Functional", PRE_01, "Tab: Rings", ""),
    ("PLP-013", "B. Category Nav", "Earrings tab", "Click Earrings tab", "Earrings products shown", "P0", "Functional", PRE_01, "Tab: Earrings", ""),
    ("PLP-014", "B. Category Nav", "Necklaces tab", "Click Necklaces tab", "Necklace products shown", "P0", "Functional", PRE_01, "Tab: Necklaces", ""),
    ("PLP-015", "B. Category Nav", "Pendants tab", "Click Pendants tab", "Pendant products shown", "P1", "Functional", PRE_01, "Tab: Pendants", ""),
    ("PLP-016", "B. Category Nav", "Bracelets tab", "Click Bracelets tab", "Bracelet products shown", "P1", "Functional", PRE_01, "Tab: Bracelets", ""),
    ("PLP-017", "B. Category Nav", "Bangles tab", "Click Bangles tab", "Bangle products shown", "P1", "Functional", PRE_01, "Tab: Bangles", ""),
    ("PLP-018", "B. Category Nav", "Nose pins tab", "Click Nose Pins tab", "Nose pin products shown", "P1", "Functional", PRE_01, "Tab: Nose Pins", ""),
    ("PLP-019", "B. Category Nav", "Tab preserves collection param", "Open /jewellery?collection=alankara; switch to Rings tab", "collection=alankara preserved in URL", "P0", "Functional", PRE_01, "?collection=alankara", ""),
    ("PLP-020", "B. Category Nav", "Tab preserves occasion param", "Open /jewellery?occasion=wedding; switch category tab", "occasion=wedding preserved", "P0", "Functional", PRE_01, "?occasion=wedding", ""),
    ("PLP-021", "B. Category Nav", "Tab preserves price params", "Apply minPrice/maxPrice; switch tab", "minPrice and maxPrice preserved in URL", "P1", "Functional", PRE_01, "Price params in URL", ""),
    ("PLP-022", "B. Category Nav", "Browser back after tab change", "Switch tabs then browser Back", "Previous category restored via popstate", "P2", "Navigation", PRE_01, "Route: /jewellery", ""),
    ("PLP-023", "B. Category Nav", "Primary listing ?category= mode", "Open /jewellery?collection=x&category=rings", "Stays on /jewellery; category encoded as query param", "P0", "Functional", PRE_01, "?collection=&category=rings", ""),
    ("PLP-024", "B. Category Nav", "Drawer single category → tab nav", "On /jewellery select one main category in drawer → Apply", "Navigates to that category tab", "P1", "Functional", PRE_01, "Filter drawer", ""),
    # C. Filter Panel
    ("PLP-025", "C. Filter Panel", "Open filter drawer", "Click FILTER in toolbar", "Drawer opens (bottom mobile, right desktop)", "P0", "Functional", PRE_01, "Route: /jewellery", ""),
    ("PLP-026", "C. Filter Panel", "Close filter drawer", "Open filters → close without apply", "Drawer closes; product list unchanged", "P1", "Functional", PRE_01, "Route: /jewellery", ""),
    ("PLP-027", "C. Filter Panel", "Apply disabled by default", "Open filters without changes", "Apply Filters button disabled", "P1", "UX", PRE_01, "Route: /jewellery", ""),
    ("PLP-028", "C. Filter Panel", "Draft vs applied state", "Change filter without Apply", "Product grid does not update until Apply clicked", "P0", "Functional", PRE_01, "Route: /jewellery", ""),
    ("PLP-029", "C. Filter Panel", "Clear All resets filters", "Apply filters → Clear All", "All drawer filters reset; listing refreshes", "P0", "Functional", PRE_01, "Route: /jewellery", ""),
    ("PLP-030", "C. Filter Panel", "Multiple filters combined", "Select Metal Type + Metal Purity → Apply", "Products match both filter conditions", "P0", "Functional", PRE_01, "Metal filters", ""),
    ("PLP-031", "C. Filter Panel", "Subcategory chips on category PLP", "Open /diamond-rings → Filters", "By Categories shows subcategory chips with heading", "P1", "UI", PRE_01, "Route: /diamond-rings", ""),
    ("PLP-032", "C. Filter Panel", "Gemstone dropdown", "Open filters → select gemstone", "Gemstone Type dropdown lists Magento options", "P1", "Functional", PRE_01, "Route: /jewellery", ""),
    ("PLP-033", "C. Filter Panel", "Clear gemstone selection", "Select gemstone then clear via sentinel", "Gemstone filter removed on Apply", "P2", "Functional", PRE_01, "Gemstone dropdown", ""),
    # D. Price Range Filter
    ("PLP-034", "D. Price Filter", "Default price range", "Open filters without changes", "Slider and Min/Max show catalog facet range", "P0", "Functional", PRE_01, "Route: /jewellery", ""),
    ("PLP-035", "D. Price Filter", "Slider min thumb", "Drag left thumb higher → Apply", "Products below min excluded; minPrice in URL", "P0", "Functional", PRE_01, "Route: /jewellery", ""),
    ("PLP-036", "D. Price Filter", "Slider max thumb", "Drag right thumb lower → Apply", "Products above max excluded; maxPrice in URL", "P0", "Functional", PRE_01, "Route: /jewellery", ""),
    ("PLP-037", "D. Price Filter", "Manual min entry", "Type min amount → Apply", "Slider syncs; filtered list updates", "P0", "Functional", PRE_01, "Min: 100000", ""),
    ("PLP-038", "D. Price Filter", "Manual max entry", "Type max amount → Apply", "Slider syncs; filtered list updates", "P0", "Functional", PRE_01, "Max: 500000", ""),
    ("PLP-039", "D. Price Filter", "Empty max = no upper limit", "Clear Max field and blur", "Treated as catalog max (no upper cap)", "P1", "Functional", PRE_01, "Route: /jewellery", ""),
    ("PLP-040", "D. Price Filter", "Min greater than max validation", "Set Min > Max", "Error shown; Apply disabled", "P0", "Validation", PRE_01, "Min: 500000, Max: 200000", ""),
    ("PLP-041", "D. Price Filter", "Below facet min validation", "Enter negative or below-catalog min", "Validation error; Apply blocked", "P1", "Validation", PRE_01, "Min: -1", ""),
    ("PLP-042", "D. Price Filter", "Above facet max validation", "Enter amount above catalog max", "Error: cannot exceed catalog max", "P1", "Validation", PRE_01, "Max above facet", ""),
    ("PLP-043", "D. Price Filter", "URL deep link minPrice", "Open /jewellery?minPrice=100000", "Filter applied on load; URL preserved", "P0", "Functional", PRE_01, "?minPrice=100000", ""),
    ("PLP-044", "D. Price Filter", "URL deep link maxPrice", "Open /jewellery?maxPrice=300000", "Filter applied on load", "P0", "Functional", PRE_01, "?maxPrice=300000", ""),
    ("PLP-045", "D. Price Filter", "URL refresh preserves price", "Apply price filter → refresh page", "Same filter still applied", "P0", "Functional", PRE_01, "Price in URL", ""),
    ("PLP-046", "D. Price Filter", "Single catalog price message", "Category where all products same price", "Message shown; no interactive slider", "P2", "Edge case", PRE_01, "Single-price category", ""),
    ("PLP-047", "D. Price Filter", "Narrow span hides slider", "Category with price span < ₹500", "Manual Min/Max only; slider hidden", "P2", "Edge case", PRE_01, "Narrow price span", ""),
    ("PLP-048", "D. Price Filter", "Category switch reclamps price", "Apply price on Rings → switch to Earrings", "Price bounds reconciled to new facet range", "P1", "Functional", PRE_01, "Tab switch", ""),
    ("PLP-049", "D. Price Filter", "Tax-index client refinement", "Apply price filter", "Displayed prices match incl-tax final_price after client refine", "P1", "Functional", PRE_01, "Price filter active", "Tax mismatch workaround"),
    # E. URL-driven Filters
    ("PLP-050", "E. URL Filters", "Collection deep link", "Open /jewellery?collection=alankara", "Collection-filtered products shown", "P0", "Functional", PRE_01, "?collection=alankara", ""),
    ("PLP-051", "E. URL Filters", "Occasion deep link", "Open /jewellery?occasion=wedding", "Occasion-filtered products shown", "P0", "Functional", PRE_01, "?occasion=wedding", ""),
    ("PLP-052", "E. URL Filters", "Diamond shape deep link", "Open /jewellery?diamondShape=round", "Shape-filtered products shown", "P1", "Functional", PRE_01, "?diamondShape=round", ""),
    ("PLP-053", "E. URL Filters", "Fancy colour deep link", "Open /jewellery?fancyColour=yellow", "Colour-filtered products shown", "P1", "Functional", PRE_01, "?fancyColour=yellow", ""),
    ("PLP-056", "E. URL Filters", "Invalid collection slug", "Open /jewellery?collection=invalid-slug-xyz", "Graceful empty state or unfiltered fallback", "P2", "Negative", PRE_01, "Invalid slug", ""),
    ("PLP-057", "E. URL Filters", "Combined collection + category", "Open /jewellery?collection=x&category=rings", "Both filters apply; primary listing URL pattern", "P0", "Functional", PRE_01, "Combined params", ""),
    # F. Sort
    ("PLP-058", "F. Sort", "Default Featured sort", "Load /jewellery", "Products in Magento position/featured order", "P0", "Functional", PRE_01, "Sort: featured", ""),
    ("PLP-059", "F. Sort", "Price Low to High", "Select Price: Low to High", "Products reorder ascending by price", "P0", "Functional", PRE_01, "Sort: price-asc", ""),
    ("PLP-060", "F. Sort", "Price High to Low", "Select Price: High to Low", "Products reorder descending by price", "P0", "Functional", PRE_01, "Sort: price-desc", ""),
    ("PLP-061", "F. Sort", "Name A to Z", "Select Name: A to Z", "Products in alphabetical order", "P1", "Functional", PRE_01, "Sort: name-asc", ""),
    ("PLP-062", "F. Sort", "Sort + filter combo", "Apply metal filter then change sort", "Filtered set re-sorted correctly", "P0", "Functional", PRE_01, "Filter + sort", ""),
    ("PLP-063", "F. Sort", "Sort searching overlay", "Change sort", "isSearching overlay shown during refetch", "P2", "UX", PRE_01, "Route: /jewellery", ""),
    ("PLP-064", "F. Sort", "Sort lost on refresh", "Change sort → full page refresh", "Sort resets to Featured (not in URL)", "P1", "Gap", PRE_01, "Refresh", "PLP-ISSUE-002"),
    ("PLP-065", "F. Sort", "Mobile sort drawer", "On mobile open Sort", "Bottom drawer with sort options", "P1", "UI", PRE_03, "Mobile", ""),
    ("PLP-066", "F. Sort", "Desktop sort select", "On desktop open Sort", "Select dropdown overlay", "P1", "UI", PRE_03, "Desktop", ""),
    # G. Load More
    ("PLP-067", "G. Load More", "Initial page size", "Load PLP with >9 products", "First 9 products shown; progress X of Y", "P0", "Functional", PRE_01, "PAGE_SIZE=9", ""),
    ("PLP-068", "G. Load More", "Load more click", "Click LOAD MORE", "Next 9 products appended", "P0", "Functional", PRE_01, ">18 products", ""),
    ("PLP-069", "G. Load More", "No duplicate products", "Load more multiple times", "No duplicate product cards in grid", "P0", "Functional", PRE_01, ">18 products", ""),
    ("PLP-070", "G. Load More", "Load more with filter", "Apply filter → load more", "Additional pages respect active filters", "P0", "Functional", PRE_01, "Filter + load more", ""),
    ("PLP-071", "G. Load More", "Load more with sort", "Change sort → load more", "Appended products maintain sort order", "P1", "Functional", PRE_01, "Sort + load more", ""),
    ("PLP-072", "G. Load More", "Load more hidden while searching", "Change sort/filter", "Load more section hidden during isSearching", "P2", "UX", PRE_01, "Route: /jewellery", ""),
    ("PLP-073", "G. Load More", "Load more aria-live", "Click load more", "sr-only aria-live announces loading", "P3", "Accessibility", PRE_01, "Route: /jewellery", ""),
    ("PLP-074", "G. Load More", "End of catalog", "Load until all products shown", "Load more hidden when hasMore=false", "P1", "Functional", PRE_01, "Small category", ""),
    # H. Product Cards & PDP
    ("PLP-075", "H. Product Cards", "Card renders name", "Inspect product card", "Product name visible", "P0", "Functional", PRE_01, "Route: /jewellery", ""),
    ("PLP-076", "H. Product Cards", "Card renders price", "Inspect product card", "Price displayed (incl-tax final_price)", "P0", "Functional", PRE_01, "Route: /jewellery", ""),
    ("PLP-077", "H. Product Cards", "Card renders image", "Inspect product card", "Primary image loads with alt text", "P0", "Functional", PRE_01, "Route: /jewellery", ""),
    ("PLP-078", "H. Product Cards", "Navigate to PDP", "Click product card", "Opens /product/{urlKey}", "P0", "Navigation", PRE_01, "Any product", ""),
    ("PLP-079", "H. Product Cards", "Metal purity on PDP link", "Apply metal purity filter → click product", "PDP URL includes ?purity= when applicable", "P1", "Functional", PRE_01, "Metal purity filter", ""),
    ("PLP-080", "H. Product Cards", "Image swipe on mobile", "Swipe product images on mobile card", "Secondary images accessible via swipe", "P2", "UI", PRE_03, "Mobile", ""),
    ("PLP-081", "H. Product Cards", "PLP price matches PDP", "Compare price on card vs PDP", "Prices consistent for same SKU", "P0", "Data", PRE_01, "Any product", ""),
    # I. Wishlist
    ("PLP-082", "I. Wishlist", "Toggle wishlist on card", "Click heart icon on product card", "Wishlist state toggles", "P1", "Functional", PRE_05, "Route: /jewellery", ""),
    ("PLP-083", "I. Wishlist", "Wishlist persists logged in", "Add to wishlist while logged in → refresh", "Item remains wishlisted", "P1", "Functional", PRE_05, "Logged-in user", ""),
    ("PLP-084", "I. Wishlist", "Wishlist guest behavior", "Toggle wishlist as guest", "Appropriate login prompt or local state per app rules", "P2", "Functional", PRE_05, "Guest user", ""),
    # J. Empty State & Errors
    ("PLP-085", "J. Empty State", "No products match filter", "Apply filter matching zero products", "Empty state with Clear Filters CTA", "P0", "Functional", PRE_01, "Extreme price range", ""),
    ("PLP-086", "J. Empty State", "Clear from empty state", "Click Clear Filters on empty state", "Filters reset; full listing returns", "P0", "Functional", PRE_01, "Filtered empty", ""),
    ("PLP-087", "J. Empty State", "Empty category", "Open category with no Magento products", "Appropriate empty state (no crash)", "P2", "Edge case", PRE_01, "Empty category", ""),
    ("PLP-088", "J. Error Handling", "Magento API failure", "Simulate listing API 500/timeout", "User-friendly error state with retry", "P0", "Resilience", PRE_01, "API failure", "PLP-ISSUE-001"),
    ("PLP-089", "J. Error Handling", "Connectivity loss", "Disconnect network during load more", "Error/retry mechanism shown", "P1", "Resilience", PRE_01, "Network off", "PLP-ISSUE-001"),
    # K. SEO & Metadata
    ("PLP-090", "K. SEO", "Page title from CMS", "Inspect <title>", "CMS SEO title used", "P1", "SEO", PRE_02, "Route: /jewellery", ""),
    ("PLP-091", "K. SEO", "Meta description from CMS", "Inspect meta description", "CMS description used", "P1", "SEO", PRE_02, "Route: /jewellery", ""),
    ("PLP-092", "K. SEO", "Canonical URL", "Inspect canonical link", "Points to /jewellery (or CMS canonical)", "P1", "SEO", PRE_02, "Route: /jewellery", ""),
    ("PLP-093", "K. SEO", "noIndex on gift-finder params", "Open PLP with gift-finder search params", "robots noindex set", "P2", "SEO", PRE_01, "Gift finder URL", ""),
    ("PLP-094", "K. SEO", "noIndex on ?category= mode", "Open /jewellery?collection=x&category=rings", "noIndex: true in metadata", "P2", "SEO", PRE_01, "?category=rings", "PLP-ISSUE-005"),
    # L. Mobile & Responsive
    ("PLP-095", "L. Responsive", "Mobile layout", "View PLP at 375px", "No horizontal scroll; cards stack correctly", "P0", "UI", PRE_03, "375px", ""),
    ("PLP-096", "L. Responsive", "Mobile filter drawer", "Open filters on mobile", "Bottom drawer; Apply/Clear reachable", "P0", "UI", PRE_03, "Mobile", ""),
    ("PLP-097", "L. Responsive", "Desktop filter panel", "Open filters on desktop", "Right-side sheet panel", "P1", "UI", PRE_03, "Desktop ≥1280px", ""),
    ("PLP-098", "L. Responsive", "Category nav horizontal scroll", "View category tabs on mobile", "Horizontal scroll; all tabs reachable", "P1", "UI", PRE_03, "Mobile", ""),
    ("PLP-099", "L. Responsive", "Toolbar product count", "View toolbar", "X Products count displayed", "P2", "UI", PRE_01, "Route: /jewellery", ""),
    # M. SSR & Performance
    ("PLP-100", "M. Performance", "SSR prefetch on /jewellery", "Load /jewellery (no gift-finder params)", "initialListing passed; no hydration refetch flash", "P1", "Performance", PRE_01, "Standard PLP", ""),
    ("PLP-101", "M. Performance", "Gift-finder skips prefetch", "Open PLP via gift-finder URL", "No SSR prefetch; client fetch only", "P2", "Performance", PRE_01, "Gift finder URL", "PLP-ISSUE-006"),
    ("PLP-102", "M. Performance", "Collection prefetch on SSR", "Open /jewellery?collection=alankara", "Server prefetches with collection filter", "P1", "Performance", PRE_01, "?collection=", ""),
    ("PLP-103", "M. Performance", "PLP performance marks", "Load PLP; check GA/network", "plp_performance events fired (TTFB, grid paint)", "P3", "Performance", PRE_01, "DevTools", ""),
    ("PLP-104", "M. Performance", "Listing client cache", "Navigate away and back within 60s", "Cached listing reused (no duplicate fetch)", "P2", "Performance", PRE_01, "60s TTL", ""),
    # N. Cross-entry
    ("PLP-105", "N. Cross-entry", "Homepage gifting CTA → PLP", "Click gifting section CTA on homepage", "Navigates to /jewellery with correct filter params", "P1", "Navigation", PRE_01, "Homepage CTA", ""),
    ("PLP-106", "N. Cross-entry", "Gift finder → PLP", "Complete gift finder flow", "PLP opens with occasion/price params", "P1", "Navigation", PRE_01, "Gift finder", ""),
    ("PLP-107", "N. Cross-entry", "Header nav → category PLP", "Click Rings in mega menu", "Opens category PLP", "P0", "Navigation", PRE_01, "Header nav", ""),
    ("PLP-108", "N. Cross-entry", "PLP → PDP → Back", "Open PDP from PLP → browser Back", "Returns to PLP with filters/sort preserved", "P1", "Navigation", PRE_01, "Browser back", ""),
    # O. Magento Data
    ("PLP-109", "O. Magento Data", "Product count vs Magento", "Compare PLP count to Magento admin", "Eligible visible products match", "P1", "Data", PRE_01, "Magento admin", ""),
    ("PLP-110", "O. Magento Data", "Disabled product hidden", "Disable product in Magento", "Product no longer appears after sync", "P1", "Data", PRE_01, "Magento admin", ""),
    ("PLP-111", "O. Magento Data", "Category assignment", "Verify product in Magento category", "Appears under correct PLP category tab", "P0", "Data", PRE_01, "Category mapping", ""),
    ("PLP-112", "O. Magento Data", "SKU on card matches PDP", "Note SKU on PLP card → open PDP", "Same SKU on PDP", "P0", "Data", PRE_01, "Any product", ""),
    # P. Code review / architecture
    ("PLP-113", "P. Architecture", "Dead collection fetch helper", "Search products.service.ts for fetchMagentoJewelleryCollectionPage usage", "Helper either used or removed", "P3", "Code", PRE_01, "products.service.ts", "PLP-ISSUE-008"),
    ("PLP-114", "P. Performance", "Hero LCP preload wired", "Check jewellery/page.tsx imports preloadPlpHeroLcpImages", "PLP hero images preloaded for LCP", "P3", "Performance", PRE_01, "jewellery/page.tsx", "PLP-ISSUE-007"),
]
